name: deploy to vercel

on:
  schedule:
    - cron:  '00 05 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set VERCEL_TOKEN value
        id: step_VERCEL_TOKEN
        run: |
          echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}" >> $GITHUB_ENV
      - name: Set ORGID value
        id: step_ORGID
        run: |
          echo "ORGID=${{ secrets.ORGID }}" >> $GITHUB_ENV
      - name: Set PROJECTID value
        id: step_PROJECTID
        run: |
          echo "PROJECTID=${{ secrets.PROJECTID }}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ env.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ env.ORGID }}
          vercel-project-id: ${{ env.PROJECTID}}